# Generated by Django 5.2.8 on 2025-12-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PatientScan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patient_id", models.CharField(max_length=50)),
                ("age", models.IntegerField()),
                ("scan_file", models.FileField(upload_to="scans/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("prediction", models.CharField(blank=True, max_length=20, null=True)),
                ("confidence", models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
