# Generated by Django 5.2.8 on 2026-01-30 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diagnosis", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="patientscan",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RenameField(
            model_name="patientscan",
            old_name="uploaded_at",
            new_name="created_at",
        ),
        migrations.AddField(
            model_name="patientscan",
            name="doctor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="patientscan",
            name="patient_id",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="patientscan",
            name="prediction",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
