# Generated by Django 5.2.8 on 2026-02-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diagnosis", "0002_alter_patientscan_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientscan",
            name="matrix_image",
            field=models.ImageField(blank=True, null=True, upload_to="matrices/"),
        ),
        migrations.AddField(
            model_name="patientscan",
            name="severity_stage",
            field=models.CharField(blank=True, default="N/A", max_length=100),
        ),
    ]
